version: '3.8'

services:

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: esg_oracle_db
    environment:
      - ORACLE_PASSWORD=fiap123
      - APP_USER=esg_user
      - APP_PASSWORD=esg_pass
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - esg-network

  esg-api:
    build: .
    container_name: esg_spring_api
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    networks:
      - esg-network

volumes:
  oracle-data:

networks:
  esg-network:
    driver: bridge