spring.application.name=esg
spring.datasource.url=jdbc:oracle:thin:@oracle-db:1521/freepdb1
spring.datasource.username=esg_user
spring.datasource.password=esg_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

# SpringDoc
springdoc.show-actuator=true

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
info.app.name=ESG API
info.app.version=1.0.0
info.app.description=API responsavel por gerenciar a eficiencia energetica e sustentabilidade das unidades da empresa
management.metrics.tags.application=esg-api
management.metrics.enable.all=true

api.security.token.secret=${API_SECURITY_TOKEN_SECRET}